# -*- coding: utf-8 -*-
"""102303389.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDTgCqNCWwZu6SdgDrPin55x19Q8_qCy
"""

import sys

import os
from yt_dlp import YoutubeDL

def download_videos(singer, num_videos):
    os.makedirs("downloads", exist_ok=True)

    query = f"ytsearch{num_videos}:{singer} songs"

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": "downloads/%(id)s.%(ext)s",
        "quiet": True
    }

    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([query])

from pydub import AudioSegment

def convert_to_audio():
    audio_files = []

    for file in os.listdir("downloads"):
        path = os.path.join("downloads", file)
        audio = AudioSegment.from_file(path)
        audio_files.append(audio)

    return audio_files

def cut_audios(audio_files, duration):
    clips = []
    for audio in audio_files:
        clip = audio[: duration * 1000]  # seconds → milliseconds
        clips.append(clip)
    return clips

def merge_audios(clips, output_file):
    final_audio = sum(clips)
    final_audio.export(output_file, format="mp3")

try:
    download_videos(singer, num_videos)
    audios = convert_to_audio()
    clips = cut_audios(audios, duration)
    merge_audios(clips, output_file)

    print("Mashup created successfully:", output_file)

except Exception as e:
    print("Error occurred:", e)

singer = "Sharry Mann"
num_videos = 3
duration = 30
output_file = "combined_audio.mp3"

try:
    download_videos(singer, num_videos)
    audios = convert_to_audio()
    clips = cut_audios(audios, duration)
    merge_audios(clips, output_file)
    print("Mashup created successfully:", output_file)

except Exception as e:
    print("Error occurred:", e)